sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t jarlleyr/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true jarlleyr/docker-react npm run test